server:
  address:     ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

database:
  logger:
    path: "logs/sql"
    level: "all"
    stdout: true
    ctxKeys: [ "RequestId" ]

  default: # todo  修改成自己的密码
    link: "mysql:root:huanggaoqing@tcp(127.0.0.1:3306)/blog"
    debug: true

redis:
  default:
    address: 127.0.0.1:6379
    db:      0

logger:
  level : "all"
  stdout: true



