// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "gf_blog/internal/logic/article"
	_ "gf_blog/internal/logic/introduction"
	_ "gf_blog/internal/logic/middleware"
	_ "gf_blog/internal/logic/project"
	_ "gf_blog/internal/logic/user"
)
