// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// BlogIntroduction is the golang structure of table blog_introduction for DAO operations like Where/Data.
type BlogIntroduction struct {
	g.Meta         `orm:"table:blog_introduction, do:true"`
	IntroductionId interface{} //
	UserId         interface{} //
	Content        interface{} //
	CreateTime     *gtime.Time // 创建时间
	UpdateTime     *gtime.Time // 更新时间
}
