// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// BlogProfile is the golang structure of table blog_profile for DAO operations like Where/Data.
type BlogProfile struct {
	g.Meta     `orm:"table:blog_profile, do:true"`
	ProfileId  interface{} //
	UserId     interface{} //
	Content    interface{} //
	CreateTime *gtime.Time //
	UpdateTime *gtime.Time //
}
