// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// BlogUserType is the golang structure of table blog_user_type for DAO operations like Where/Data.
type BlogUserType struct {
	g.Meta    `orm:"table:blog_user_type, do:true"`
	TypeId    interface{} //
	TypeValue interface{} //
}
