// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// BlogRole is the golang structure of table blog_role for DAO operations like Where/Data.
type BlogRole struct {
	g.Meta     `orm:"table:blog_role, do:true"`
	RoleId     interface{} //
	RoleName   interface{} //
	CreateTime *gtime.Time //
	UpdateTime *gtime.Time //
}
