// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// BlogArticle is the golang structure of table blog_article for DAO operations like Where/Data.
type BlogArticle struct {
	g.Meta         `orm:"table:blog_article, do:true"`
	ArticleId      interface{} //
	UserId         interface{} //
	ArticleContent interface{} //
	ArticleTitle   interface{} //
	IsStick        interface{} //
	GroupId        interface{} //
	CreateTime     *gtime.Time //
	UpdateTime     *gtime.Time //
}
