// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// BlogArticleDao is the data access object for table blog_article.
type BlogArticleDao struct {
	table   string             // table is the underlying table name of the DAO.
	group   string             // group is the database configuration group name of current DAO.
	columns BlogArticleColumns // columns contains all the column names of Table for convenient usage.
}

// BlogArticleColumns defines and stores column names for table blog_article.
type BlogArticleColumns struct {
	ArticleId      string //
	UserId         string //
	ArticleContent string //
	ArticleTitle   string //
	IsStick        string //
	GroupId        string //
	CreateTime     string // 创建时间
	UpdateTime     string // 更新时间
}

// blogArticleColumns holds the columns for table blog_article.
var blogArticleColumns = BlogArticleColumns{
	ArticleId:      "article_id",
	UserId:         "user_id",
	ArticleContent: "article_content",
	ArticleTitle:   "article_title",
	IsStick:        "is_stick",
	GroupId:        "group_id",
	CreateTime:     "create_time",
	UpdateTime:     "update_time",
}

// NewBlogArticleDao creates and returns a new DAO object for table data access.
func NewBlogArticleDao() *BlogArticleDao {
	return &BlogArticleDao{
		group:   "default",
		table:   "blog_article",
		columns: blogArticleColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *BlogArticleDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *BlogArticleDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *BlogArticleDao) Columns() BlogArticleColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *BlogArticleDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *BlogArticleDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *BlogArticleDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
