// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// BlogRoleEnumDao is the data access object for table blog_role_enum.
type BlogRoleEnumDao struct {
	table   string              // table is the underlying table name of the DAO.
	group   string              // group is the database configuration group name of current DAO.
	columns BlogRoleEnumColumns // columns contains all the column names of Table for convenient usage.
}

// BlogRoleEnumColumns defines and stores column names for table blog_role_enum.
type BlogRoleEnumColumns struct {
	RoleId     string //
	RoleName   string //
	CreateTime string //
	UpdateTime string //
}

// blogRoleEnumColumns holds the columns for table blog_role_enum.
var blogRoleEnumColumns = BlogRoleEnumColumns{
	RoleId:     "role_id",
	RoleName:   "role_name",
	CreateTime: "create_time",
	UpdateTime: "update_time",
}

// NewBlogRoleEnumDao creates and returns a new DAO object for table data access.
func NewBlogRoleEnumDao() *BlogRoleEnumDao {
	return &BlogRoleEnumDao{
		group:   "default",
		table:   "blog_role_enum",
		columns: blogRoleEnumColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *BlogRoleEnumDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *BlogRoleEnumDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *BlogRoleEnumDao) Columns() BlogRoleEnumColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *BlogRoleEnumDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *BlogRoleEnumDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *BlogRoleEnumDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
