// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"gf_blog/internal/model"
)

type (
	IArticle interface {
		GetList(ctx context.Context, in *model.GetArticleListInput) (out *model.GetArticleListOutput, err error)
		GetDetail(ctx context.Context, in *model.GetArticleDetailInput) (out *model.GetArticleDetailOutput, err error)
		GetTagDataByArticleId(ctx context.Context, in *model.GetTagDataByArticleIdInput) (out *model.GetTagDataByArticleIdOutput, err error)
	}
)

var (
	localArticle IArticle
)

func Article() IArticle {
	if localArticle == nil {
		panic("implement not found for interface IArticle, forgot register?")
	}
	return localArticle
}

func RegisterArticle(i IArticle) {
	localArticle = i
}
