// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"gf_blog/internal/model"
)

type (
	IIntroduction interface {
		GetByUserId(ctx context.Context, in *model.GetIntroductionByUserIdInput) (out *model.GetIntroductionByUserIdOutput, err error)
	}
)

var (
	localIntroduction IIntroduction
)

func Introduction() IIntroduction {
	if localIntroduction == nil {
		panic("implement not found for interface IIntroduction, forgot register?")
	}
	return localIntroduction
}

func RegisterIntroduction(i IIntroduction) {
	localIntroduction = i
}
