// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf_blog/internal/dao/internal"
)

// internalBlogRoleDao is internal type for wrapping internal DAO implements.
type internalBlogRoleDao = *internal.BlogRoleDao

// blogRoleDao is the data access object for table blog_role.
// You can define custom methods on it to extend its functionality as you wish.
type blogRoleDao struct {
	internalBlogRoleDao
}

var (
	// BlogRole is globally public accessible object for table blog_role operations.
	BlogRole = blogRoleDao{
		internal.NewBlogRoleDao(),
	}
)

// Fill with you ideas below.
