// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf_blog/internal/dao/internal"
)

// internalBlogUserTypeDao is internal type for wrapping internal DAO implements.
type internalBlogUserTypeDao = *internal.BlogUserTypeDao

// blogUserTypeDao is the data access object for table blog_user_type.
// You can define custom methods on it to extend its functionality as you wish.
type blogUserTypeDao struct {
	internalBlogUserTypeDao
}

var (
	// BlogUserType is globally public accessible object for table blog_user_type operations.
	BlogUserType = blogUserTypeDao{
		internal.NewBlogUserTypeDao(),
	}
)

// Fill with you ideas below.
