// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf_blog/internal/dao/internal"
)

// internalBlogArticleDao is internal type for wrapping internal DAO implements.
type internalBlogArticleDao = *internal.BlogArticleDao

// blogArticleDao is the data access object for table blog_article.
// You can define custom methods on it to extend its functionality as you wish.
type blogArticleDao struct {
	internalBlogArticleDao
}

var (
	// BlogArticle is globally public accessible object for table blog_article operations.
	BlogArticle = blogArticleDao{
		internal.NewBlogArticleDao(),
	}
)

// Fill with you ideas below.
