// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf_blog/internal/dao/internal"
)

// internalBlogProjectDao is internal type for wrapping internal DAO implements.
type internalBlogProjectDao = *internal.BlogProjectDao

// blogProjectDao is the data access object for table blog_project.
// You can define custom methods on it to extend its functionality as you wish.
type blogProjectDao struct {
	internalBlogProjectDao
}

var (
	// BlogProject is globally public accessible object for table blog_project operations.
	BlogProject = blogProjectDao{
		internal.NewBlogProjectDao(),
	}
)

// Fill with you ideas below.
