// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf_blog/internal/dao/internal"
)

// internalBlogIntroductionDao is internal type for wrapping internal DAO implements.
type internalBlogIntroductionDao = *internal.BlogIntroductionDao

// blogIntroductionDao is the data access object for table blog_introduction.
// You can define custom methods on it to extend its functionality as you wish.
type blogIntroductionDao struct {
	internalBlogIntroductionDao
}

var (
	// BlogIntroduction is globally public accessible object for table blog_introduction operations.
	BlogIntroduction = blogIntroductionDao{
		internal.NewBlogIntroductionDao(),
	}
)

// Fill with you ideas below.
