// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf_blog/internal/dao/internal"
)

// internalBlogRoleEnumDao is internal type for wrapping internal DAO implements.
type internalBlogRoleEnumDao = *internal.BlogRoleEnumDao

// blogRoleEnumDao is the data access object for table blog_role_enum.
// You can define custom methods on it to extend its functionality as you wish.
type blogRoleEnumDao struct {
	internalBlogRoleEnumDao
}

var (
	// BlogRoleEnum is globally public accessible object for table blog_role_enum operations.
	BlogRoleEnum = blogRoleEnumDao{
		internal.NewBlogRoleEnumDao(),
	}
)

// Fill with you ideas below.
