// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf_blog/internal/dao/internal"
)

// internalBlogTagAssociateDao is internal type for wrapping internal DAO implements.
type internalBlogTagAssociateDao = *internal.BlogTagAssociateDao

// blogTagAssociateDao is the data access object for table blog_tag_associate.
// You can define custom methods on it to extend its functionality as you wish.
type blogTagAssociateDao struct {
	internalBlogTagAssociateDao
}

var (
	// BlogTagAssociate is globally public accessible object for table blog_tag_associate operations.
	BlogTagAssociate = blogTagAssociateDao{
		internal.NewBlogTagAssociateDao(),
	}
)

// Fill with you ideas below.
