// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// BlogProfile is the golang structure for table blog_profile.
type BlogProfile struct {
	ProfileId  int64       `json:"profileId"  ` //
	UserId     int64       `json:"userId"     ` //
	Content    string      `json:"content"    ` //
	CreateTime *gtime.Time `json:"createTime" ` //
	UpdateTime *gtime.Time `json:"updateTime" ` //
}
