// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// BlogTag is the golang structure for table blog_tag.
type BlogTag struct {
	Id         int64       `json:"id"         ` //
	Name       string      `json:"name"       ` //
	Url        string      `json:"url"        ` //
	CreateTime *gtime.Time `json:"createTime" ` // 创建时间
	UpdateTime *gtime.Time `json:"updateTime" ` // 更新时间
}
