// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// BlogRoleEnum is the golang structure for table blog_role_enum.
type BlogRoleEnum struct {
	RoleId     int64       `json:"roleId"     ` //
	RoleName   string      `json:"roleName"   ` //
	CreateTime *gtime.Time `json:"createTime" ` //
	UpdateTime *gtime.Time `json:"updateTime" ` //
}
