// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// BlogProject is the golang structure for table blog_project.
type BlogProject struct {
	ProjectId       string      `json:"projectId"       ` // 项目Id
	ProjectName     string      `json:"projectName"     ` // 项目名称
	ProjectUrl      string      `json:"projectUrl"      ` // 项目地址
	ProjectDesc     string      `json:"projectDesc"     ` // 项目描述
	ProjectIcon     string      `json:"projectIcon"     ` // 项目图标
	ProjectIconDark string      `json:"projectIconDark" ` // 项目图标(暗色模式)
	UserId          string      `json:"userId"          ` // 用户id
	CreateTime      *gtime.Time `json:"createTime"      ` // 创建时间
	UpdateTime      *gtime.Time `json:"updateTime"      ` // 更新时间
}
