// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// BlogUserType is the golang structure for table blog_user_type.
type BlogUserType struct {
	TypeId    int    `json:"typeId"    ` //
	TypeValue string `json:"typeValue" ` //
}
