// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// BlogRole is the golang structure for table blog_role.
type BlogRole struct {
	Id         string      `json:"id"         ` // id
	RoleCode   int         `json:"roleCode"   ` // 角色id
	RoleName   string      `json:"roleName"   ` // 角色名
	UserId     string      `json:"userId"     ` // 用户id
	CreateTime *gtime.Time `json:"createTime" ` // 创建时间
	UpdateTime *gtime.Time `json:"updateTime" ` // 更新时间
}
