// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// BlogIntroduction is the golang structure for table blog_introduction.
type BlogIntroduction struct {
	IntroductionId string      `json:"introductionId" ` //
	UserId         string      `json:"userId"         ` //
	Content        string      `json:"content"        ` //
	CreateTime     *gtime.Time `json:"createTime"     ` // 创建时间
	UpdateTime     *gtime.Time `json:"updateTime"     ` // 更新时间
}
