// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// BlogTagAssociate is the golang structure for table blog_tag_associate.
type BlogTagAssociate struct {
	ArticleId string `json:"articleId" ` //
	TagId     int64  `json:"tagId"     ` //
}
