// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// BlogUser is the golang structure for table blog_user.
type BlogUser struct {
	UserId      string      `json:"userId"      ` //
	UserName    string      `json:"userName"    ` //
	Password    string      `json:"password"    ` //
	PhoneNumber string      `json:"phoneNumber" ` //
	CreateTime  *gtime.Time `json:"createTime"  ` // 创建时间
	UpdateTime  *gtime.Time `json:"updateTime"  ` // 更新时间
	Avatar      string      `json:"avatar"      ` //
	Role        int64       `json:"role"        ` //
}
